version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: pao_container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_pao
      MYSQL_USER: pao_user
      MYSQL_PASSWORD: root
    volumes:
      - ./pao.sql:/docker-entrypoint-initdb.d/pao.sql